version: '3.4'

services:
  meusistema.api:
    build:
      context: .
      dockerfile: src/MeuSistema.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT=Docker   # 👉 força o .NET a carregar appsettings.Docker.json

  db:
    image: postgres:16
    container_name: meusistema_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meusistema
    ports:
      - "5432:5432"
